
.PHONY: run
run:
	npm run start

.PHONY: format
format:
	npx prettier-eslint-cli --write 'src/**/*.{ts,tsx}'
#	npx eslint --fix 'src/**/*.{ts,tsx}'
#	npx prettier -w '**/*.{ts,tsx}'

.PHONY: lint
lint:
	npx eslint 'src/**/*.{ts,tsx}'
#	npx prettier -c 'src/**/*.{ts,tsx}'
