version: "3.8"
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
      target: "database"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: times-hub
      POSTGRES_USER: times-hub
      POSTGRES_DB: workspaces
      TZ: Asia/Tokyo
    restart: always
volumes:
  pgdata:
